WebApplication4/WebApplication4/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Utilities;

namespace WebApplication4.Controllers
{
    public class CartController : Controller
    {
        // GET: AlisverisSepet
        public ActionResult List()
        {
            if (!UserOperations.IsLogged(this.HttpContext, "User/Login"))
                return null;

            using (var context = new CYEntities())
            {
                int userID = Convert.ToInt32(Session["UserID"]);
                List<CartProduct> list = context.CartProducts.Include("Product").Where(p => p.UserID == userID && p.Status != 1).ToList();
                return View(list);
            }
        }
        [HttpPost]
        public ActionResult Add(int productID, int quantity)
        {
            if (!UserOperations.IsLogged(this.HttpContext, "User/Login"))
                return null;

            int userID = Convert.ToInt32(Session["UserID"]);
            using (var context = new CYEntities())
            {
                CartProduct cp = new CartProduct();
                cp.ProductID = productID;
                cp.Quantity = quantity;
                cp.UserID = userID;
                context.CartProducts.Add(cp);
                context.SaveChanges();
            }

            return RedirectToAction("List","Product");
        }
        [HttpPost]
        public ActionResult Remove(int id)
        {
            if (!UserOperations.IsLogged(this.HttpContext, "User/Login"))
                return null;

            using (var context = new CYEntities())
            {
                var cp = context.CartProducts.Where(p => p.ID == id).SingleOrDefault();
                if (cp != null)
                {
                    context.CartProducts.Remove(cp);
                    context.SaveChanges();
                }
            }

            return RedirectToAction("List");
        }
        [HttpPost]
        public ActionResult Update(int id,int quantity)
        {
            if (!UserOperations.IsLogged(this.HttpContext, "User/Login"))
                return null;

            using (var context = new CYEntities())
            {
                var cp = context.CartProducts.Where(p => p.ID == id).SingleOrDefault();
                cp.Quantity = quantity;
                context.SaveChanges();
            }

            return RedirectToAction("List");
        }
        public ActionResult Buy()
        {
            if (!UserOperations.IsLogged(this.HttpContext, "User/Login"))
                return null;
            using (var context = new CYEntities())
            {
                int userID = Convert.ToInt32(Session["UserID"]);
                List<CartProduct> list = context.CartProducts.Where(p => p.UserID == userID && p.Status != 1).ToList();
                if (list != null || list.Count > 0)
                {
                    foreach (var item in list)
                        item.Status = 1;

                    context.SaveChanges();
                }
            }

            return RedirectToAction("Success");
        }
        public ActionResult Success()
        {
            return View();
        }
    }
}

WebApplication4/WebApplication4/Controllers/HakkımızdaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication4.Controllers
{
    public class HakkımızdaController : Controller
    {
        // GET: Hakkımızda
        public ActionResult Hakkımızda()
        {
            return View();
        }
    }
}

WebApplication4/WebApplication4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication4.Controllers
{
    public class HomeController : Controller
    {
        // GET: Anasayfa
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApplication4/WebApplication4/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Utilities;

namespace WebApplication4.Controllers
{
    public class ProductController : Controller
    {
        // GET: Urunler
        public ActionResult List()
        {
            using (var context = new CYEntities()) {
                List<Product> list = context.Products.ToList();
                return View(list);
            }
        }
        
    }
}

WebApplication4/WebApplication4/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Utilities;

namespace WebApplication4.Controllers
{
    public class UserController : Controller
    {
        // GET: Giris
        public ActionResult Login(string r)
        {
            ViewBag.Result = r;
            return View();
        }

        [HttpPost]
        public ActionResult Register(User model)
        {
            string r = "";
            if (String.IsNullOrWhiteSpace(model.Email) || String.IsNullOrWhiteSpace(model.Password) || String.IsNullOrWhiteSpace(model.Name))
                r = "Email, parola ve isim boş bırakılamaz.";
            else
            {
                using (var context = new CYEntities())
                {
                    model.Password = MD5.Hash(model.Password);
                    context.Users.Add(model);

                    context.SaveChanges();
                }
            }
            return RedirectToAction("Login", new { r = r });
        }
        [HttpPost]
        public ActionResult Login(User model)
        {
            string r = "";
            if (String.IsNullOrWhiteSpace(model.Email) || String.IsNullOrWhiteSpace(model.Password))
                r = "Email ve isim boş bırakılamaz.";
            else
            {
                using (var context = new CYEntities())
                {
                    model.Password = MD5.Hash(model.Password);
                    var user = context.Users.Where(p => p.Email == model.Email && p.Password == model.Password).FirstOrDefault();
                    if (user != null)
                    {
                        Session["UserID"] = user.ID;
                        Session["UserEmail"] = user.Email;
                        Session["UserName"] = user.Name;
                        Session["UserAddress"] = user.Address;

                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            return RedirectToAction("Login", new { r = r });
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Account()
        {
            if (!UserOperations.IsLogged(this.HttpContext, "User/Login"))
                return null;

            using(var context = new CYEntities())
            {
                int userID = Convert.ToInt32(Session["UserID"]);
                User user = context.Users.Where(p => p.ID == userID).FirstOrDefault();
                return View(user);
            }
        }
        [HttpPost]
        public ActionResult Account(User model)
        {
            if (!UserOperations.IsLogged(this.HttpContext, "User/Login"))
                return null;

            if (String.IsNullOrWhiteSpace(model.Email) || String.IsNullOrWhiteSpace(model.Password) || String.IsNullOrWhiteSpace(model.Name))
                ViewBag.Error = "Email, parola ve isim boş bırakılamaz.";
            else
            {
                model.Password = MD5.Hash(model.Password);
                using (var context = new CYEntities())
                {
                    int userID = Convert.ToInt32(Session["UserID"]);
                    User user = context.Users.Where(p => p.ID == userID).FirstOrDefault();
                    user.Name = model.Name;
                    user.Password = model.Password;
                    user.Email = model.Email;
                    user.Address = model.Address;
                    context.SaveChanges();

                    Session["UserEmail"] = user.Email;
                    Session["UserName"] = user.Name;
                    Session["UserAddress"] = user.Address;
                }
            }

            return Account();
        }
    }
}

WebApplication4/WebApplication4/Controllers/İletisimController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication4.Controllers
{
    public class İletisimController : Controller
    {
        // GET: İletisim
        public ActionResult İletisim()
        {
            return View();
        }
    }
}

WebApplication4/WebApplication4/Views/Cart/List.cshtml
@model List<CartProduct>
@{
    ViewBag.Title = "sepet";
    Layout = "~/Views/Shared/Layout.cshtml";
}

    <div class="container checking-area">
        <div class="row">
            <div class="col-md-9 cart-area">
                <div class="sixteen columns cart-section oflow">
                    <!-- Cart -->
                    <table class="table cart-table responsive-table" style="white-space:nowrap;">
                        <tr>
                            <th>
                                Resim
                            </th>
                            <th>
                                Ürün Adı
                            </th>
                            <th>
                                Ücret
                            </th>
                            <th>
                                Miktar
                            </th>
                            <th>
                                 Tutar
                            </th>
                            <th>
                            </th>
                        </tr>
                        @if (Model != null && Model.Count > 0)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        <img src="@Url.Content(item.Product.ImagePath)" alt="" style="width:100px" />
                                    </td>
                                    <td class="cart-title">
                                        <a href="#">@item.Product.Name</a>
                                    </td>
                                    <td>
                                        @item.Product.Price TL
                                    </td>
                                    <td>
                                        <form action='Update' method="post">
                                            <input type="hidden" name="id" value="@item.ID" />
                                            <input type='text' name="quantity" value='@item.Quantity' class="qty" />
                                            <input type="submit" value="Güncelle" class="btn btn-primary" style="margin-left:10px;" />
                                        </form>
                                    </td>
                                    <td class="cart-total">
                                        @(item.Product.Price * item.Quantity)TL
                                    </td>
                                    <td>
                                        <form action='Remove' method="post">
                                            <input type="hidden" name="id" value="@item.ID" />
                                            <input type="submit" value="Sil" class="btn btn-danger" />
                                        </form>
                                    </td>
                                </tr>
                            }
                        } else
                        {
                            <tr><td colspan="100%">Sepetinizde ürün bulunmuyor.</td></tr>
                        }
                    </table>
                    @if (Model != null && Model.Count > 0)
                    {
                        <a href="Buy" class="btn btn-primary btn-block">Satın Al</a>
                    }
                </div>
                <!-- Start -->
                <!-- end -->
            </div>
            <!-- Sidebar -->
           
        </div>
    </div>

WebApplication4/WebApplication4/Views/Cart/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Success</h2>

WebApplication4/WebApplication4/Views/Hakkımızda/Hakkımızda.cshtml
@{
    ViewBag.Title = "Hakkımızda";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<!doctype html>
<html lang="en" class="no-js">
<head>
    <meta charset="utf-8">
    <title>delicio</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css" media="screen">
    <link rel="stylesheet" type="text/css" href="css/style.css" media="screen">
    <link rel="stylesheet" type="text/css" href="css/font-awesome.css" media="screen">
    <link rel="stylesheet" href="css/responsive.css" type="text/css" media="screen" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
</head>
<body>

 
    <div class="container">
        <div class="row bottom-strip">
            <div class="col-md-6 rights">
                <p>
                    <h1>MERT DEMİRTÜRK</h1>
                    <h2>MERVE AYDIN</h2>
                </p>
            </div>

        </div>
    </div>
    </div>
    <!--end-footer-->
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.js"></script>
    <script type="text/javascript" src="js/script.js"></script>
    <script src="js/modernizr.js"></script>
    <script type="text/javascript" src="js/jquery.nouislider.min.js"></script>
</body>
</html>

WebApplication4/WebApplication4/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Anasayfa";
    Layout = "~/Views/Shared/Layout.cshtml";
}
@section HeadCss {
    <link rel="stylesheet" href="~/Content/css/flexslider.css" type="text/css" media="screen" />  
}
@section Scripts {     
    <script src="~/Scripts/jquery.flexslider.js"></script>
    <script type="text/javascript">
        // jQuery
        (function ($) {
            "use strict";
            $(document).ready(function () {
                // Main Slider
                $('.main-flexslider').flexslider({
                    directionNav: true,
                    controlNav: false,
                    animation: "fade",
                    slideshowSpeed: 7000,
                    prevText: "",
                    nextText: "",
                });
            });
        })(jQuery);
    </script>
}

<div class="main-flexslider">
    <ul class="slides">
        <li class="slides">
            <img src="~/Content/img/AnasayfaSlider.jpg" alt="slide 01">
            <div class="slide-caption">
                <h2>Çikolatan Yanında</h2>
                <h2>Dünya Çikolataları</h2>
                <h2><a href="#">Tekliflerimiz</a></h2>
            </div>
        </li>
        <li class="slides">
            <img src="~/Content/img/slide-02.jpg" alt="slide 01">
            <div class="slide-caption">
                <h2>Çikolatan Yanında</h2>
                <h2>Dünya Çikolataları</h2>
                <h2><a href="#">Tekliflerimiz</a></h2>
            </div>
        </li>
        <li class="slides">
            <img src="~/Content/img/slide-03.jpg" alt="slide 01">
            <div class="slide-caption">
                <h2>Çikolatan Yanında</h2>
                <h2>Dünya Çikolataları</h2>
                <h2><a href="#">Tekliflerimiz</a></h2>
            </div>
        </li>
        <li class="slides">
            <img src="~/Content/img/slide-04.jpg" alt="slide 01">
            <div class="slide-caption">
                <h2>Çikolatan Yanında</h2>
                <h2>Dünya Çikolataları</h2>
                <h2><a href="#">Tekliflerimiz</a></h2>
            </div>
        </li>
    </ul>
</div>

<div class="container">
    <div class="icon-blocks">
        <div class="col-md-4">
            <p>
                <i class="fa fa-group"></i>personalized shop
            </p>
        </div>
        <div class="col-md-4">
            <p>
                <i class="fa fa-bell"></i>email notification
            </p>
        </div>
        <div class="col-md-4">
            <p>
                <i class="fa fa-globe"></i>worldwide shipping
            </p>
        </div>
    </div>
</div>

WebApplication4/WebApplication4/Views/Product/List.cshtml
@model List<Product>
@{
    ViewBag.Title = "Urunler";
    Layout = "~/Views/Shared/Layout.cshtml";
}
    <!-- shop-page -->
    <div class="container checking-area">
        <div class="row">
            <div class="col-md-9 cart-area">
                <div class="sixteen columns cart-section oflow">
                    <!-- Cart -->
                    <table class="table cart-table responsive-table" style="white-space:nowrap;">
                        <tr>
                            <th>
                                Resim
                            </th>
                            <th>
                                Adı
                            </th>
                            <th>
                                Ücret
                            </th>
                            <th>
                                Miktar
                            </th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <img src="@Url.Content(item.ImagePath)" style="width:200px;" alt="" />
                                </td>
                                <td class="cart-title">
                                    <a href="#">@item.Name</a>
                                </td>
                                <td>
                                    @item.Price TL
                                </td>
                                <td>
                                    <form action='@Url.Content("~/Cart/Add")' method="post">
                                        <div class="qtyminus">
                                        </div>
                                        <input type="hidden" name="productID" value="@item.ID" />
                                        <input type='text' name="quantity" value='1' class="qty" />
                                        <input type="submit" class="btn btn-primary" value="Ekle" style="margin-left:5px;" />
                                    </form>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
                <!-- Start -->
                <!-- end -->
            </div>
            <!-- Sidebar -->
           
        </div>
    </div>

WebApplication4/WebApplication4/Views/Shared/Layout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>delicio</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap.css" media="screen">
    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css" media="screen">
    <link rel="stylesheet" type="text/css" href="~/Content/css/font-awesome.css" media="screen">
    <link rel="stylesheet" href="~/Content/css/responsive.css" type="text/css" media="screen" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'> 
    @if(IsSectionDefined("HeadCss"))
    {
        @RenderSection("HeadCss")
    }
</head>


<body>
    <!--top-strip-->
    <div class="top-strip">
        <div class="container">
            <div class="row">
                <div class="col-md-6 user">
                    <p>
                        ÇikolatanYanında'ya Hoşgeldiniz
                    </p>
                </div>
                <div class="col-md-6 language">
                    <ul>
                        @if (WebApplication4.Utilities.UserOperations.IsLogged(this.Context))
                        {

                            <li>@Html.ActionLink(Session["UserName"].ToString(), "Account", "User")</li>
                            <li>@Html.ActionLink("Çıkış", "Logout", "User")</li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Giris&Kaydol", "Login", "User")</li>
                        }
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!--end-top-strip-->
    <!--navbar-->
    <div class="container header"> 
        <nav id="myNavbar" class="navbar navbar-default" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#"><img src="C:\Users\Mert\Desktop\delicio\images\footer-logo" alt="logo"></a>
                </div>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                    
                        <li class="active">@Html.ActionLink("Anasayfa","Index","Home")</li>
                        <li>@Html.ActionLink("Urunler","List","Product")</li>
                        @if (Session["UserID"] != null)
                        {
                            int cartCount = 0;
                            using (var context = new CYEntities())
                            {
                                int userID = Convert.ToInt32(Session["UserID"]);
                                List<CartProduct> cList = context.CartProducts.Where(p => p.UserID == userID && p.Status != 1).ToList();
                                foreach (var item in cList)
                                {
                                    cartCount += (int)item.Quantity;
                                }
                                if (cartCount > 0)
                                {
                                    <li>@Html.ActionLink("Sepetiniz("+cartCount+")", "List", "Cart")</li>
                                }
                                else
                                {
                                    <li>@Html.ActionLink("Sepetiniz", "List", "Cart")</li>
                                }
                            }

                        }
                        @if (Session["UserID"] == null)
                        {
                            <li>@Html.ActionLink("Giris", "Login", "User")</li>
                        }
                        <li>@Html.ActionLink("Hakkımızda", "Hakkımızda", "Hakkımızda")</li>  
                        <li>@Html.ActionLink("İLETİSİM", "İletisim", "İletisim")</li>
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
        </nav>
    </div>
    @if (ViewBag.Result != null)
    {
        <div class="alert alert-danger" style="margin:20px;">
            <strong>Dikkat !</strong> @ViewBag.Result
        </div>
    }
    @RenderBody()
        <!--end-navbar-->
        <!--footer-->
    <div class="full-footer">
        <div class="container-full">
            <div class="container info">
                <div class="row">
                    <div class="col-md-4 addres">
                        <img src="images/footer-logo.png" alt="">
                        <h6>ÇikolatanYanında</h6>
                        <p>
                            Sakarya
                        </p>
                        <p>
                            Telefon 0123 32112332
                        </p>
                    </div>
                    <div class="col-md-2 account">
                        <h4>Hesabım</h4>
                        <ul>
                            <li><a href="#">Sepet</a></li>                          
                            <li><a href="#">Hesap</a></li>
                        </ul>
                    </div>
                  
                    <div class="col-md-4 about">
                        <h4>Hakkımızda</h4>
                        <p>
                            Dünyanın en iyi çikolatalarını sizin için bir araya getirdik.
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!--end-addres-->
        <div class="container">
            <div class="row bottom-strip">
                <div class="col-md-6 rights">
                    <p>
                        Tüm hakları saklıdır
                    </p>
                </div>
                <div class="col-md-6 social">
                    <ul>
                        <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-asterisk"></i></a></li>
                        <li><a href="#"><i class="fa fa-facebook-square"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
        <!--end-footer-->
    
    <script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap.js"></script>
    <script type="text/javascript" src="~/Scripts/modernizr.js"></script>
    @if (IsSectionDefined("Scripts"))
    {
        @RenderSection("Scripts")
    }
    </body>
</html>

WebApplication4/WebApplication4/Views/User/Account.cshtml
@model WebApplication4.User
@{
    ViewBag.Title = "Account";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<div class="container checking-area">
    <div class="row">
        <div class="col-md-9 checkout-accordion">
            <div class="col-md-12 white-bg">
                <div class="bs-example">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">1. Checkout Method</a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in panel-body">
                                <div class="accordion-list-content" style="overflow: hidden; display: block;">
                                    <div class="col-md-12 check-name">
                                        <h4>returning costumer</h4>
                                        <div>
                                            <form class="form-horizontal" role="form" action="" method="post">
                                                <div class="form-group">
                                                    <label class="col-md-4">İsim</label>
                                                    <div class="col-md-8">
                                                        <input type="text" name="Name" class="form-control" placeholder="İsim" value="@Model.Name">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-md-4">Email</label>
                                                    <div class="col-sm-8">
                                                        <input type="email" name="Email" class="form-control" placeholder="Email" value="@Model.Email">
                                                    </div>
                                                </div>

                                                <div class="form-group">
                                                    <label class="col-md-4">Parola</label>
                                                    <div class="col-sm-8">
                                                        <input type="password" name="Password" class="form-control" placeholder="Parola">
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <label class="col-md-4">Adres</label>
                                                    <div class="col-sm-8">
                                                        <textarea class="form-control" name="Address" placeholder="Adres">@Model.Address</textarea>
                                                    </div>
                                                </div>
                                                <input type="submit" value="Güncelle" class="btn btn-primary" />
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>